global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "vois-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
